# Generated by Django 4.0.3 on 2022-03-07 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text_question', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HI', 'history'), ('SC', 'science'), ('SP', 'sports'), ('AR', 'art'), ('GE', 'geography'), ('EN', 'entertaiment'), ('NC', 'no category')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text_answer', models.CharField(max_length=150)),
                ('correct_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
