# Generated by Django 4.0.2 on 2022-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('HI', 'history'), ('SC', 'science'), ('SP', 'sports'), ('AR', 'art'), ('GE', 'geography'), ('EN', 'entertaiment'), ('NC', 'no category')], max_length=2),
        ),
    ]
