# Generated by Django 4.0.2 on 2022-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_text_questions_questionuser_text_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaryuser',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
